name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - run: npm install

      - run: npm run build

      - run: npm install -g firebase-tools

      - run: firebase deploy --only hosting --token "${{ secrets.serverless }}"
